version: 2

sources:
  - name: air_quality
    description: "Fuentes de datos crudos recolectados mediante APIs oficiales"
    database: air_quality_db  # Definición explícita de la base de datos
    schema: raw            # Definición explícita del esquema
    freshness:
      warn_after: {count: 2, period: hour}
      error_after: {count: 6, period: hour}
    loaded_at_field: ingested_at
    tables:
      - name: valencia_air_real_hourly
        description: "Tabla con los datos horarios en tiempo real de la API de Valencia"
        columns:
          - name: station_id
            description: "Identificador único de la estación (mapeado desde objectid)"
            tests:
              - not_null      # Garantiza que cada medida esté asociada a una estación
          - name: measure_timestamp
            description: "Timestamp de cuándo se tomó la medición (de la API)"
            tests:
              - not_null
          
          - name: ingested_at
            description: "Timestamp de cuándo guardamos el dato en nuestra BD"
            tests:
              - not_null
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - station_id
                - measure_timestamp
              config:
                severity: error  # Falla el build si hay duplicados
                error_if: ">0"   # Cualquier duplicado es error crítico

      # - name: raw.madrid_air
      #   description: "Tabla con los datos crudos de la API de Madrid (formato JSONB)"
      #   columns:
      #     - name: station_id
      #       description: "Identificador único de la estación de Madrid"
      #       tests:
      #         - not_null