
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'air_quality_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'air_quality_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  air_quality_dbt:
    # Materialize staging models as views, intermediate and marts as tables
    staging:
      +materialized: view
      +tags: ["staging"]
      +schema: staging
    intermediate:
      +materialized: table
      +tags: ["intermediate"]
      +schema: intermediate
    marts:
      +materialized: table
      +tags: ["marts"]
      +schema: marts
