air_quality_dbt:
  outputs:
    dev:
      dbname: air_quality_db
      host: db
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
      # Suprimir warnings de PostgreSQL (solo mostrar errores)
      client_min_messages: error
  target: dev